server:
  port: 8761
eureka:
  # 默认情况下 eureka server同时也是eureka client,用于相互注册形成高可用的eureka服务
  # 单点时 如果registerWithEureka配置为true 则会报错
  client:
    register-with-eureka: false         # 是否注册到eureka服务，默认true 当前已为eureka server 故配置为false
    fetch-registry: false               # 是否在本地缓存注册信息，默认true 当前为单点eureka server,不需要从其他eureka获取注册信息，更不用说缓存了，故配置为false
    service-url:
      default-zone: http://127.0.0.1:8761/eureka
  server:
    # 自我保护机制
    enable-self-preservation: true      # 本地调试时可false关闭，生产建议打开，防止因网络不稳定等原因导致误删服务

# 指定生效配置
spring:
  profiles:
    active: dev
  application:
    name: eureka       # 启动的服务名
  freemarker:
    prefer-file-system-access: false